name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          # Install PyInstaller and only required runtime deps to avoid conflicting packages in requirements.txt
          python -m pip install --upgrade pyinstaller
          # Install PyTMX and pygame (pick one pygame implementation). Avoid installing both pygame and pygame-ce.
          python -m pip install PyTMX==3.32
          python -m pip install pygame==2.6.1

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          # Add data folders if they exist; PyInstaller on Windows expects SRC;DEST
          $addDataArgs = @()
          if (Test-Path data)   { $addDataArgs += "--add-data \"data;data\"" }
          if (Test-Path images) { $addDataArgs += "--add-data \"images;images\"" }
          if (Test-Path sounds) { $addDataArgs += "--add-data \"sounds;sounds\"" }
          $baseArgs = "--noconfirm --onefile --name DhaaguduMoothalu"
          $cmd = "pyinstaller $baseArgs $($addDataArgs -join ' ') client.py"
          Write-Host "Running: $cmd"
          Invoke-Expression $cmd

      - name: Show dist contents
        shell: pwsh
        run: |
          if (Test-Path dist) { Get-ChildItem -Recurse dist | ForEach-Object { Write-Host $_.FullName } } else { Write-Host "No dist directory found" }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DhaaguduMoothalu-dist
          path: dist/
